sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t deekasun/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true deekasun/docker-react npm run test -- --coverage


